### ISSUE TITLE
enable 'python setup.py develop'?

### ISSUE THREAD

**Issue by DanHickstein** [ycasg/PyNLO#5]
Is there a reason that PyNLO uses
```python
from distutils.core import setup
```
rather than
```python
from setuptools import setup
```

setuptools has the advantage that it allows the use of [`python setup.py develop`](http://stackoverflow.com/questions/19048732/python-setup-py-develop-vs-install) in order to allow the user to modify the source code and use it without needing to reinstall the package. 
@ycasg

**Comment by ycasg** [comment]
No, the default was simply because distutils is more standard. Setuptools seems to work easily, so the requested change has been made.

**Comment by DanHickstein** [comment]
Thanks!
