### ISSUE TITLE
Is it possible to generate the pulse with a measured spectrum

### ISSUE THREAD

**Issue by WeiWenKevinChen** [ycasg/PyNLO#56]
We recorded our laser spectrum with OSA (csv file). How can we generate a pulse using the OSA spectrum for the simulation? We also have the FROG trace of our 40fs pulsed laser.

**Comment by DanHickstein** [comment]
I've never done this, and I don't think that there is any super easy way already implemented in PyNLO. But, you can certainly set the (complex valued) intensity of the pulse in either the time of frequency domain using the [pulse.set_AW](https://github.com/pyNLO/PyNLO/blob/master/src/pynlo/light/PulseBase.py#L203) or set_AT functions.

From your FROG, you should be able to get the `amplitude` and `phase` at all of the `frequencies`. The only weird part is that you need to interpolate to the frequency grid used by the pulse. After creating a pulse object, I would probably try something like:

```python
interp = scipy.interpolate.interp1d(frequencies * 2 * np.pi, amplitude*np.exp(1j * phase), fill_value=0)
aw = pulse.get_AW()
pulse.set_AW(interp(aw))
```

Then you could set the pulse energy using `pulse.set_epp`.

Let me know if that makes sense. I'd imagine that other people would want to do the same thing, so if you wanted to implement a function in the pulse class that accepts the frequencies, amplitudes, and (optionally) phases, I'm sure that people would appreciate it.

**Comment by DanHickstein** [comment]
Oh, alternatively, there is a "FROGPulse" class that seems to do what you're looking for: https://github.com/pyNLO/PyNLO/blob/master/src/pynlo/light/DerivedPulses.py#L123

**Comment by WeiWenKevinChen** [comment]
Thanks for your reply. I will try to do so.
